service: ro
image: alca42/ro

servers:
  web:
    - 49.13.146.41

proxy:
  ssl: true
  host: canis.run
  app_port: 4000

registry:
  username: alca42

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  args:
    VITE_PUBLIC_SERVER: "https://api.canis.run"

env:
  clear:
    NODE_ENV: "production"
    PORT: 4000
  secret:
    - DATABASE_URL

accessories:
  zero:
    image: rocicorp/zero:0.12.2025012501-3203d0
    roles:
      - web
    env:
      clear:
        ZERO_REPLICA_FILE: "/data/zstart_replica.db"
        ZERO_SCHEMA_FILE: "/data/zero-schema.json"
      secret:
        - ZERO_UPSTREAM_DB
        - ZERO_CVR_DB
        - ZERO_CHANGE_DB
        - ZERO_AUTH_SECRET
    proxy:
      ssl: true
      host: api.canis.run
      app_port: 4848
      healthcheck:
        interval: 5
        path: "/"
        timeout: 3
    files:
      - zero-schema.json:/data/zero-schema.json
    directories:
      - data:/data

  postgres:
    image: postgres:17
    roles:
      - web
    env:
      clear:
        POSTGRES_USER: "ro"
        POSTGRES_DB: "ro"
        POSTGRES_HOST_AUTH_METHOD: "md5"
        POSTGRES_INITDB_ARGS: "--auth-host=md5"
      secret:
        - POSTGRES_PASSWORD
    cmd: |
      postgres \
        -c wal_level=logical \
        -c max_wal_senders=10 \
        -c max_replication_slots=5 \
        -c hot_standby=on \
        -c hot_standby_feedback=on
    port: "5432:5432"
    directories:
      - data:/var/lib/postgresql/data
